# Generated by Django 5.2.1 on 2025-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='encrypted_vote',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_commitment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_nonce',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_signature',
            field=models.TextField(null=True),
        ),
    ]
