# Generated by Django 5.2.1 on 2025-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote_encrypted_vote_vote_vote_commitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='encrypted_vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_commitment',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_nonce',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_signature',
        ),
        migrations.AddField(
            model_name='election',
            name='rsa_public_key_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
